services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
      - wrangler-local-state:/app/.wrangler
    ports:
      - "3001:3001"
    command: sh -c "yarn install && yarn dev"

volumes:
  wrangler-local-state: