services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./shared:/shared
      - /app/node_modules
      - wrangler-local-state:/app/.wrangler
    ports:
      - "3001:3001"
    command: sh -c "yarn install && yarn dev"
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./shared:/shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: sh -c "yarn install && yarn dev --host"

volumes:
  wrangler-local-state: