services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
      - wrangler-local-state:/app/.wrangler
    ports:
      - "3000:3000"

volumes:
  wrangler-local-state: